steps:
    - id: 'tf init'
      name: 'hashicorp/terraform'      
      args: ['init']      

    - id: 'tf plan'
      name: 'hashicorp/terraform'      
      env:
        - GOOGLE_CLOUD_KEYFILE_JSON = tfsvc.json
      args: ['plan']        

    - id: 'tf apply'
      name: 'hashicorp/terraform'      
      env:
        - GOOGLE_CLOUD_KEYFILE_JSON = tfsvc.json
        - TF_VAR_env=dev
        - TF_LOG=DEBUG        
      args: ['apply','auto-approve']
        
          
        