steps:
    - id: 'tf init'      
      entrypoint: 'sh'      
      args:
        - '-C'
        - |
          terraform init 

    - id: 'tf plan'      
      entrypoint: 'sh'
      env:
        - GOOGLE_CLOUD_KEYFILE_JSON = tfsvc.json
      args:
        - '-C'
        - |
          terraform plan 

    - id: 'tf apply'      
      entrypoint: 'sh'
      env:
        - GOOGLE_CLOUD_KEYFILE_JSON = tfsvc.json              
      args:
        - '-C'
        - |
          terraform apply
          
        